### ISSUE TITLE
TaskCancelledException bad behavior

### ISSUE THREAD

**Issue by softlion** [msmolka/ZNetCS.AspNetCore.Compression#2]
When TaskCancelledException is thrown because a request is cancelled, this lib throws an exception.

Instead, it should not, as this is 'normal' behavior.

```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ZNetCS.AspNetCore.Compression.Compressors.CompressorBase.CompressAsync(Stream inputStream, Stream outputStream, CancellationToken cancellationToken)
   at ZNetCS.AspNetCore.Compression.Infrastructure.CompressionExecutor.ExecuteAsync(HttpContext context, Stream bufferedStream, ICollection`1 compressors, CancellationToken cancellationToken)
   at ZNetCS.AspNetCore.Compression.CompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

**Comment by msmolka** [comment]
The lib is not throwing any task exception. It is as well not catching any of them.

**Comment by a90machado** [comment]
Any news around this? Someone has solved or find the real problem around this error?

**Comment by msmolka** [comment]
Like I was written before lib is not doing anything with cancelling. It just passes cancellation token when request is aborted
